Inventory index page
ajc113/inventory pull request #6
Opened 2023-07-18 18:02 UTC by gullariz12

Loom:
https://www.loom.com/share/1473df8eb88b43aeab852e1ce3a487fc

2023-07-18 20:19 UTC, ajc113 approved these changes

2023-07-19 02:13 UTC, tannakartikey requested changes
Can we create a `dev:prime` task to priming the database with a little bit of test data.

Just 2-3 locations and 5 flavors should do. Inventory can be random number between 1 to 15. So we can just write a small loop to generate the data.

2023-07-19 02:13 UTC, tannakartikey commented on app/controllers/dashboard_controller.rb
> +    @flavors = Flavor.includes(:location_flavors).order(name: :asc)
Let's define `ordered_by_name` method on the model.

2023-07-19 16:59 UTC, tannakartikey approved these changes

2023-07-19 17:04 UTC, merged